name: CUDA-12.6

on:
  push:
    branches:
      - cuda-12.6

env:
  BUILD_VERSION: "12.6.3"
  IMAGE_NAME: registry.cn-qingdao.aliyuncs.com/wod/cuda

jobs:
  cuda-ubuntu22:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.cn-qingdao.aliyuncs.com
          username: ${{ secrets.REGISTRY_USER_ALIYUN }}
          password: ${{ secrets.REGISTRY_PASSWORD_ALIYUN }}

      - name: Build and push AMD64 image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./cuda/dockerfile
          platforms: linux/amd64
          push: true
          provenance: false
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.BUILD_VERSION }}-runtime-ubuntu22.04
          build-args: |
            BASE=nvidia/cuda:${{ env.BUILD_VERSION }}-runtime-ubuntu22.04
            AUTHOR=${{ github.repository_owner }}
            VERSION=${{ env.BUILD_VERSION }}

      - name: Build complete
        run: echo "CUDA ${{ env.BUILD_VERSION }}-runtime-ubuntu22.04 pushed successfully!"

  cudnn-ubuntu22:
    runs-on: ubuntu-latest
    needs: cuda-ubuntu22

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.cn-qingdao.aliyuncs.com
          username: ${{ secrets.REGISTRY_USER_ALIYUN }}
          password: ${{ secrets.REGISTRY_PASSWORD_ALIYUN }}

      - name: Build and push AMD64 image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./cuda/dockerfile
          platforms: linux/amd64
          push: true
          provenance: false
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.BUILD_VERSION }}-cudnn-runtime-ubuntu22.04
          build-args: |
            BASE=nvidia/cuda:${{ env.BUILD_VERSION }}-cudnn-runtime-ubuntu22.04
            AUTHOR=${{ github.repository_owner }}
            VERSION=${{ env.BUILD_VERSION }}

      - name: Build complete
        run: echo "CUDA ${{ env.BUILD_VERSION }}-cudnn-runtime-ubuntu22.04 pushed successfully!"
