name: IDE-CUDA

on:
  push:
    branches:
      - ide-cuda

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      BUILD_VERSION: 12.6.3-devel-ubuntu24.04
      IMAGE_NAME: registry.cn-qingdao.aliyuncs.com/wod/ide

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.cn-qingdao.aliyuncs.com
          username: ${{ secrets.REGISTRY_USER_ALIYUN }}
          password: ${{ secrets.REGISTRY_PASSWORD_ALIYUN }}

      - name: Build and push AMD64 image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./ide-cuda/dockerfile
          platforms: linux/amd64
          push: true
          provenance: false
          tags: |
            ${{ env.IMAGE_NAME }}:cuda${{ env.BUILD_VERSION }}
          build-args: |
            BASE=nvidia/cuda:${{ env.BUILD_VERSION }}

      - name: Build complete
        run: echo "IDE-CUDA image pushed successfully!"
