name: MySQL-5

on:
  push:
    branches:
      - mysql-5

env:
  BUILD_VERSION: 5.7.42

jobs:
  mysql-oraclelinux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Calculate release version
        id: version
        run: |
          RELEASE_VERSION=$(echo "${{ env.BUILD_VERSION }}" | cut -d. -f1,2)
          echo "release=$RELEASE_VERSION" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.cn-qingdao.aliyuncs.com
          username: ${{ secrets.REGISTRY_USER_ALIYUN }}
          password: ${{ secrets.REGISTRY_PASSWORD_ALIYUN }}

      - name: Build and push AMD64 image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./mysql/dockerfile
          platforms: linux/amd64
          push: true
          provenance: false
          tags: |
            registry.cn-qingdao.aliyuncs.com/wod/mysql:${{ env.BUILD_VERSION }}
            registry.cn-qingdao.aliyuncs.com/wod/mysql:${{ env.BUILD_VERSION }}-amd64
            registry.cn-qingdao.aliyuncs.com/wod/mysql:${{ steps.version.outputs.release }}
          build-args: |
            BASE=mysql:${{ env.BUILD_VERSION }}
            AUTHOR=${{ github.repository_owner }}
            VERSION=${{ env.BUILD_VERSION }}

      - name: Image push success
        run: echo "Docker images pushed successfully to registry.cn-qingdao.aliyuncs.com/wod/mysql"

  mysql-debian:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Calculate release version
        id: version
        run: |
          RELEASE_VERSION=$(echo "${{ env.BUILD_VERSION }}" | cut -d. -f1,2)
          echo "release=$RELEASE_VERSION" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.cn-qingdao.aliyuncs.com
          username: ${{ secrets.REGISTRY_USER_ALIYUN }}
          password: ${{ secrets.REGISTRY_PASSWORD_ALIYUN }}

      - name: Build and push AMD64 image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./mysql/dockerfile
          platforms: linux/amd64
          push: true
          provenance: false
          tags: |
            registry.cn-qingdao.aliyuncs.com/wod/mysql:${{ env.BUILD_VERSION }}-debian
            registry.cn-qingdao.aliyuncs.com/wod/mysql:${{ env.BUILD_VERSION }}-debian-amd64
            registry.cn-qingdao.aliyuncs.com/wod/mysql:${{ steps.version.outputs.release }}-debian
          build-args: |
            BASE=mysql:${{ env.BUILD_VERSION }}-debian
            AUTHOR=${{ github.repository_owner }}
            VERSION=${{ env.BUILD_VERSION }}

      - name: Image push success
        run: echo "Docker images pushed successfully to registry.cn-qingdao.aliyuncs.com/wod/mysql"
