name: New API

on:
  push:
    branches:
      - newapi

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      BUILD_VERSION: v0.9.22

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: |
            image=moby/buildkit:master
            network=host

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.cn-qingdao.aliyuncs.com
          username: ${{ secrets.REGISTRY_USER_ALIYUN }}
          password: ${{ secrets.REGISTRY_PASSWORD_ALIYUN }}

      - name: Build and push multi-platform Docker images
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./new-api/dockerfile
          push: true
          tags: |
            registry.cn-qingdao.aliyuncs.com/wod/new-api:${{ env.BUILD_VERSION }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            BASE=calciumion/new-api:${{ env.BUILD_VERSION }}
            AUTHOR=${{ github.repository_owner }}
            VERSION=${{ env.BUILD_VERSION }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Build and push AMD64 image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./new-api/dockerfile
          platforms: linux/amd64
          push: true
          provenance: false
          tags: |
            registry.cn-qingdao.aliyuncs.com/wod/new-api:${{ env.BUILD_VERSION }}-amd64
          build-args: |
            BASE=calciumion/new-api:${{ env.BUILD_VERSION }}
            AUTHOR=${{ github.repository_owner }}
            VERSION=${{ env.BUILD_VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push ARM64 image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./new-api/dockerfile
          platforms: linux/arm64
          push: true
          provenance: false
          tags: |
            registry.cn-qingdao.aliyuncs.com/wod/new-api:${{ env.BUILD_VERSION }}-arm64
          build-args: |
            BASE=calciumion/new-api:${{ env.BUILD_VERSION }}
            AUTHOR=${{ github.repository_owner }}
            VERSION=${{ env.BUILD_VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
