name: node-22

on:
  push:
    branches:
      - node-22

env:
  BUILD_VERSION: 22.21.1

jobs:
  node-alpine:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Calculate release version
        id: version
        run: |
          RELEASE_VERSION=$(echo "${{ env.BUILD_VERSION }}" | cut -d. -f1)
          echo "release=$RELEASE_VERSION" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: |
            image=moby/buildkit:master
            network=host

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v2
        with:
          registry: registry.cn-qingdao.aliyuncs.com
          username: ${{ secrets.REGISTRY_USER_ALIYUN }}
          password: ${{ secrets.REGISTRY_PASSWORD_ALIYUN }}

      - name: Build and push multi-platform Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./node/alpine.dockerfile
          push: true
          tags: |
            registry.cn-qingdao.aliyuncs.com/wod/node:${{ env.BUILD_VERSION }}-alpine
            registry.cn-qingdao.aliyuncs.com/wod/node:${{ steps.version.outputs.release }}-alpine
          platforms: linux/amd64,linux/arm64
          build-args: |
            BASE=node:${{ env.BUILD_VERSION }}-alpine
            AUTHOR=${{ github.repository_owner }}
            VERSION=${{ env.BUILD_VERSION }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Build and push AMD64 Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./node/alpine.dockerfile
          push: true
          tags: |
            registry.cn-qingdao.aliyuncs.com/wod/node:${{ env.BUILD_VERSION }}-alpine-amd64
          platforms: linux/amd64
          build-args: |
            BASE=node:${{ env.BUILD_VERSION }}-alpine
            AUTHOR=${{ github.repository_owner }}
            VERSION=${{ env.BUILD_VERSION }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Build and push ARM64 Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./node/alpine.dockerfile
          push: true
          tags: |
            registry.cn-qingdao.aliyuncs.com/wod/node:${{ env.BUILD_VERSION }}-alpine-arm64
          platforms: linux/arm64
          build-args: |
            BASE=node:${{ env.BUILD_VERSION }}-alpine
            AUTHOR=${{ github.repository_owner }}
            VERSION=${{ env.BUILD_VERSION }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Image push success
        run: echo "Docker images and manifests pushed successfully to registry.cn-qingdao.aliyuncs.com/wod/node"

  node-debian:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Calculate release version
        id: version
        run: |
          RELEASE_VERSION=$(echo "${{ env.BUILD_VERSION }}" | cut -d. -f1)
          echo "release=$RELEASE_VERSION" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: |
            image=moby/buildkit:master
            network=host

      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v2
        with:
          registry: registry.cn-qingdao.aliyuncs.com
          username: ${{ secrets.REGISTRY_USER_ALIYUN }}
          password: ${{ secrets.REGISTRY_PASSWORD_ALIYUN }}

      - name: Build and push multi-platform Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./node/debian.dockerfile
          push: true
          tags: |
            registry.cn-qingdao.aliyuncs.com/wod/node:${{ env.BUILD_VERSION }}
            registry.cn-qingdao.aliyuncs.com/wod/node:${{ steps.version.outputs.release }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            BASE=node:${{ env.BUILD_VERSION }}
            AUTHOR=${{ github.repository_owner }}
            VERSION=${{ env.BUILD_VERSION }}

      - name: Build and push AMD64 Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./node/debian.dockerfile
          push: true
          tags: |
            registry.cn-qingdao.aliyuncs.com/wod/node:${{ env.BUILD_VERSION }}-amd64
          platforms: linux/amd64
          build-args: |
            BASE=node:${{ env.BUILD_VERSION }}
            AUTHOR=${{ github.repository_owner }}
            VERSION=${{ env.BUILD_VERSION }}

      - name: Build and push ARM64 Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./node/debian.dockerfile
          push: true
          tags: |
            registry.cn-qingdao.aliyuncs.com/wod/node:${{ env.BUILD_VERSION }}-arm64
          platforms: linux/arm64
          build-args: |
            BASE=node:${{ env.BUILD_VERSION }}
            AUTHOR=${{ github.repository_owner }}
            VERSION=${{ env.BUILD_VERSION }}

      - name: Image push success
        run: echo "Docker images and manifests pushed successfully to registry.cn-qingdao.aliyuncs.com/wod/node"
