name: OpenWRT

on:
  push:
    branches:
      - openwrt-v24.10

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: |
            image=moby/buildkit:master
            network=host

      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.cn-qingdao.aliyuncs.com
          username: ${{ secrets.REGISTRY_USER_ALIYUN }}
          password: ${{ secrets.REGISTRY_PASSWORD_ALIYUN }}

      - name: Build and push x86-64 Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./openwrt/dockerfile
          push: true
          tags: |
            registry.cn-qingdao.aliyuncs.com/wod/openwrt-imagebuilder:x86-64-v24.10.4
          platforms: linux/amd64
          build-args: |
            BASE=openwrt/imagebuilder:x86-64-v24.10.4
            AUTHOR=${{ github.repository_owner }}
            VERSION=v24.10.4

      - name: Build and push rockchip-armv8 Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./openwrt/dockerfile
          push: true
          tags: |
            registry.cn-qingdao.aliyuncs.com/wod/openwrt-imagebuilder:rockchip-armv8-v24.10.4
          platforms: linux/amd64
          build-args: |
            BASE=openwrt/imagebuilder:rockchip-armv8-v24.10.4
            AUTHOR=${{ github.repository_owner }}
            VERSION=v24.10.4
