name: PaddlePaddle

on:
  push:
    branches:
      - paddlepaddle

jobs:
  pull-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.cn-qingdao.aliyuncs.com
          username: ${{ secrets.REGISTRY_USER_ALIYUN }}
          password: ${{ secrets.REGISTRY_PASSWORD_ALIYUN }}

      - name: Pull PaddlePaddle official image
        run: |
          docker pull paddlepaddle/paddle:2.6.0-gpu-cuda12.0-cudnn8.9-trt8.6

      - name: Tag and push PaddlePaddle image (without -amd64)
        run: |
          docker tag paddlepaddle/paddle:2.6.0-gpu-cuda12.0-cudnn8.9-trt8.6 registry.cn-qingdao.aliyuncs.com/wod/paddlepaddle:2.6.0-gpu-cuda12.0-cudnn8.9-trt8.6
          docker push registry.cn-qingdao.aliyuncs.com/wod/paddlepaddle:2.6.0-gpu-cuda12.0-cudnn8.9-trt8.6

      - name: Tag and push PaddlePaddle image (with -amd64)
        run: |
          docker tag paddlepaddle/paddle:2.6.0-gpu-cuda12.0-cudnn8.9-trt8.6 registry.cn-qingdao.aliyuncs.com/wod/paddlepaddle:2.6.0-gpu-cuda12.0-cudnn8.9-trt8.6-amd64
          docker push registry.cn-qingdao.aliyuncs.com/wod/paddlepaddle:2.6.0-gpu-cuda12.0-cudnn8.9-trt8.6-amd64

      - name: Clean up local images
        run: |
          docker rmi paddlepaddle/paddle:2.6.0-gpu-cuda12.0-cudnn8.9-trt8.6 || true
          docker rmi registry.cn-qingdao.aliyuncs.com/wod/paddlepaddle:2.6.0-gpu-cuda12.0-cudnn8.9-trt8.6 || true
          docker rmi registry.cn-qingdao.aliyuncs.com/wod/paddlepaddle:2.6.0-gpu-cuda12.0-cudnn8.9-trt8.6-amd64 || true