name: PyTorch 2.1

on:
  push:
    branches:
      - pytorch-2.1
  workflow_dispatch:

jobs:
  pull-and-push:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 1
      matrix:
        variant:
          - runtime
          - devel

    env:
      SOURCE_IMAGE: pytorch/pytorch:2.1.2-cuda12.1-cudnn8-${{ matrix.variant }}
      TARGET_IMAGE: registry.cn-qingdao.aliyuncs.com/wod/pytorch:2.1.2-cuda12.1-cudnn8-${{ matrix.variant }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.cn-qingdao.aliyuncs.com
          username: ${{ secrets.REGISTRY_USER_ALIYUN }}
          password: ${{ secrets.REGISTRY_PASSWORD_ALIYUN }}

      - name: Pull PyTorch official image
        run: docker pull ${{ env.SOURCE_IMAGE }}

      - name: Tag and push PyTorch image
        run: |
          docker tag ${{ env.SOURCE_IMAGE }} ${{ env.TARGET_IMAGE }}
          docker push ${{ env.TARGET_IMAGE }}
          docker tag ${{ env.SOURCE_IMAGE }} ${{ env.TARGET_IMAGE }}-amd64
          docker push ${{ env.TARGET_IMAGE }}-amd64

      - name: Clean up local images
        run: |
          docker rmi ${{ env.SOURCE_IMAGE }} || true
          docker rmi ${{ env.TARGET_IMAGE }} || true
          docker rmi ${{ env.TARGET_IMAGE }}-amd64 || true
