name: signoz

on:
  push:
    branches:
      - signoz

env:
  SIGNOZ_VERSION: v0.107.0
  OTEL_VERSION: v0.129.12

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v2
        with:
          registry: registry.cn-qingdao.aliyuncs.com
          username: ${{ secrets.REGISTRY_USER_ALIYUN }}
          password: ${{ secrets.REGISTRY_PASSWORD_ALIYUN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push signoz
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./signoz/signoz.dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          provenance: false
          tags: |
            registry.cn-qingdao.aliyuncs.com/wod/signoz:${{ env.SIGNOZ_VERSION }}
            ghcr.io/${{ github.repository_owner }}/signoz:${{ env.SIGNOZ_VERSION }}
          build-args: |
            BASE=signoz/signoz:${{ env.SIGNOZ_VERSION }}

      - name: Build and push otel-collector
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./signoz/otel-collector.dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          provenance: false
          tags: |
            registry.cn-qingdao.aliyuncs.com/wod/signoz:otel-collector-${{ env.OTEL_VERSION }}
            ghcr.io/${{ github.repository_owner }}/signoz:otel-collector-${{ env.OTEL_VERSION }}
          build-args: |
            BASE=signoz/signoz-otel-collector:${{ env.OTEL_VERSION }}

      - name: Build and push schema-migrator
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./signoz/schema-migrator.dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          provenance: false
          tags: |
            registry.cn-qingdao.aliyuncs.com/wod/signoz:schema-migrator-${{ env.OTEL_VERSION }}
            ghcr.io/${{ github.repository_owner }}/signoz:schema-migrator-${{ env.OTEL_VERSION }}
          build-args: |
            BASE=signoz/signoz-schema-migrator:${{ env.OTEL_VERSION }}

      - name: All images built
        run: echo "All SigNoz images built and pushed successfully!"
